'use client';

import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Compass, Bot, Network, ArrowRight, ClipboardList, Route, MessageSquare, Quote, PlayCircle } from 'lucide-react';
import Logo from '@/components/logo';
import { UserNav } from '@/components/user-nav';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { auth } from '@/lib/firebase';
import { onAuthStateChanged } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const features = [
  {
    icon: <Compass className="w-8 h-8 text-primary" />,
    title: 'Interactive Assessment',
    description: 'Uncover your passions, skills, and values through our comprehensive Ikigai assessment.',
    imageId: 'feature1',
  },
  {
    icon: <Bot className="w-8 h-8 text-primary" />,
    title: 'AI-Powered Recommendations',
    description: 'Receive personalized career paths and actionable roadmaps generated by our advanced AI.',
    imageId: 'feature2',
  },
  {
    icon: <Network className="w-8 h-8 text-primary" />,
    title: 'Dynamic Roadmap',
    description: 'Visualize your career journey, customize milestones, and track your progress towards success.',
    imageId: 'feature3',
  },
];

const howItWorksSteps = [
    {
        icon: <ClipboardList className="w-10 h-10 text-primary" />,
        title: "1. Take the Assessment",
        description: "Answer a series of thought-provoking questions to uncover your unique passions, strengths, and motivations."
    },
    {
        icon: <Route className="w-10 h-10 text-primary" />,
        title: "2. Generate Your Roadmap",
        description: "Our AI analyzes your results to create a personalized career roadmap with actionable steps and milestones."
    },
    {
        icon: <MessageSquare className="w-10 h-10 text-primary" />,
        title: "3. Chat with Your Counselor",
        description: "Refine your path and get answers to your questions with Kai, your personal AI career counselor."
    }
];

const testimonials = [
    {
        name: "Sarah L.",
        role: "Career Changer",
        quote: "IKI-G-AI gave me the clarity I was desperately looking for. The roadmap wasn't just a list of jobs; it was a genuine reflection of who I am. I finally feel confident in my career change.",
        avatarId: "testimonial1"
    },
    {
        name: "Michael B.",
        role: "Recent Graduate",
        quote: "As a recent grad, the job market felt overwhelming. This platform helped me connect my degree to a mission I care about. The AI counselor was surprisingly insightful for interview prep!",
        avatarId: "testimonial2"
    },
    {
        name: "Jessica Y.",
        role: "Product Manager",
        quote: "I was feeling stuck in my career. The Ikigai assessment helped me rediscover what I love, and the AI showed me how to pivot within my own company. It's been a game-changer.",
        avatarId: "testimonial3"
    }
];

const faqs = [
    {
        question: "What is Ikigai?",
        answer: "Ikigai is a Japanese concept that means 'a reason for being.' It's about finding the intersection of what you love, what you're good at, what the world needs, and what you can be paid for. Our platform is designed to help you discover your personal Ikigai."
    },
    {
        question: "How does the AI generate my roadmap?",
        answer: "Our advanced AI analyzes your answers from the assessment. It identifies patterns and connections between your passions, skills, and values to suggest career paths that align with your unique profile. It provides not just job titles, but a complete roadmap with actionable steps."
    },
    {
        question: "Is my personal data secure?",
        answer: "Absolutely. We prioritize your privacy. Your assessment data is stored securely and is only used to personalize your experience within the app. We do not share your personal information with third parties."
    },
    {
        question: "Can I change my roadmap later?",
        answer: "Yes! Your career journey is dynamic, and so is your roadmap. You can re-order steps, and as you grow and your interests evolve, you can retake the assessment to generate a new, updated roadmap at any time."
    }
]

const heroImage = PlaceHolderImages.find((p) => p.id === 'hero');
const copilotImage = PlaceHolderImages.find((p) => p.id === 'copilot');
const whyIkigaiImage = PlaceHolderImages.find((p) => p.id === 'why-ikigai');
const videoThumbnail = PlaceHolderImages.find((p) => p.id === 'video-thumbnail');
const careerPreviewImage = PlaceHolderImages.find((p) => p.id === 'career-preview');


export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState<boolean | null>(null);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setIsLoggedIn(!!user);
    });
    return () => unsubscribe();
  }, []);

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center">
          <Logo />
          <div className="flex flex-1 items-center justify-end space-x-4">
            {isLoggedIn !== null && (
              isLoggedIn ? <UserNav /> : (
                <Button asChild>
                  <Link href="/login">Sign In & Get Started</Link>
                </Button>
              )
            )}
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="relative pt-24 pb-32 md:pt-32 md:pb-40 lg:pt-40 lg:pb-48">
           {heroImage && (
            <Image
              src={heroImage.imageUrl}
              alt={heroImage.description}
              fill
              className="object-cover"
              priority
              data-ai-hint={heroImage.imageHint}
            />
          )}
          <div className="absolute inset-0 bg-background/60 backdrop-blur-sm" />
          <div className="container relative text-center">
            <div className="bg-accent/30 text-accent-foreground rounded-full px-4 py-1.5 text-sm font-medium bg-purple-500/20 text-purple-800 dark:text-purple-200 inline-block mb-4">
              Find Your Purpose. Build Your Future.
            </div>
            <h1 className="font-headline text-4xl md:text-6xl font-bold tracking-tighter mb-6 text-foreground">
              Navigate Your Career with <span className="text-primary">IKI-G-AI</span>
            </h1>
            <p className="max-w-2xl mx-auto text-lg text-foreground/80 mb-8">
              Discover your life's purpose and translate it into a personalized, AI-driven career roadmap.
            </p>
            <Button asChild size="lg">
              <Link href="/dashboard">Get Started Now</Link>
            </Button>
          </div>
        </section>

        <section id="features" className="py-24 bg-card border-y">
          <div className="container">
            <div className="text-center mb-16">
              <h2 className="font-headline text-3xl md:text-4xl font-bold">A Smarter Way to Plan Your Career</h2>
              <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                Our platform integrates self-discovery with AI precision to guide you on a fulfilling professional journey.
              </p>
            </div>
            <div className="grid md:grid-cols-3 gap-8">
              {features.map((feature) => {
                const image = PlaceHolderImages.find((p) => p.id === feature.imageId);
                return (
                  <Card key={feature.title} className="flex flex-col overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300">
                    <CardHeader className="flex flex-row items-center gap-4 p-6">
                      {feature.icon}
                      <CardTitle className="font-headline m-0">{feature.title}</CardTitle>
                    </CardHeader>
                    <CardContent className="flex-grow p-6 pt-0">
                      <p className="text-muted-foreground">{feature.description}</p>
                    </CardContent>
                    <div className="aspect-video relative">
                      {image && (
                        <Image src={image.imageUrl} alt={feature.title} fill className="object-cover" data-ai-hint={image.imageHint} />
                      )}
                    </div>
                  </Card>
                );
              })}
            </div>
          </div>
        </section>
        
        <section id="why-ikigai" className="py-24">
          <div className="container grid md:grid-cols-2 gap-12 items-center">
            <div className="relative aspect-square rounded-xl overflow-hidden shadow-2xl">
              {whyIkigaiImage && (
                <Image src={whyIkigaiImage.imageUrl} alt={whyIkigaiImage.description} fill className="object-cover" data-ai-hint={whyIkigaiImage.imageHint} />
              )}
            </div>
            <div>
              <h2 className="font-headline text-3xl md:text-4xl font-bold">What is Ikigai?</h2>
              <p className="text-muted-foreground mt-4 mb-6 text-lg">
                Ikigai (生き甲斐) is a Japanese concept that means "a reason for being." It's the source of value in one's life or the things that make one's life worthwhile. It’s about finding the intersection where your passions and talents converge with the things that the world needs and is willing to pay for.
              </p>
              <p className="text-muted-foreground text-lg">Our platform is designed to guide you through this process of self-discovery, helping you find clarity, purpose, and a career that truly fulfills you.</p>
            </div>
          </div>
        </section>

        <section id="how-it-works" className="py-24 bg-card border-y">
            <div className="container">
                <div className="text-center mb-16">
                    <h2 className="font-headline text-3xl md:text-4xl font-bold">Your Journey to Purpose in 3 Simple Steps</h2>
                    <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                        We've streamlined the path to discovering and acting on your Ikigai.
                    </p>
                </div>
                <div className="grid md:grid-cols-3 gap-8 text-center">
                    {howItWorksSteps.map((step) => (
                        <div key={step.title} className="flex flex-col items-center">
                            <div className="flex items-center justify-center h-20 w-20 rounded-full bg-primary/10 mb-6">
                                {step.icon}
                            </div>
                            <h3 className="font-headline text-xl font-bold mb-2">{step.title}</h3>
                            <p className="text-muted-foreground">{step.description}</p>
                        </div>
                    ))}
                </div>
            </div>
        </section>

        <section id="video-walkthrough" className="py-24">
            <div className="container">
                <div className="text-center mb-12">
                    <h2 className="font-headline text-3xl md:text-4xl font-bold">See IKI-G-AI in Action</h2>
                    <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                        Watch this short video to see how you can go from uncertainty to a clear career path in minutes.
                    </p>
                </div>
                <div className="relative aspect-video max-w-4xl mx-auto rounded-xl overflow-hidden shadow-2xl cursor-pointer group">
                    {videoThumbnail && (
                        <Image src={videoThumbnail.imageUrl} alt={videoThumbnail.description} fill className="object-cover" data-ai-hint={videoThumbnail.imageHint} />
                    )}
                    <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
                        <PlayCircle className="w-24 h-24 text-white/80 transform transition-transform group-hover:scale-110" />
                    </div>
                </div>
            </div>
        </section>

        <section className="py-24 bg-card border-y">
          <div className="container grid md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="font-headline text-3xl md:text-4xl font-bold">Your Personal Career Co-Pilot</h2>
              <p className="text-muted-foreground mt-4 mb-6">
                Go beyond static career advice. Our platform provides everything you need to take control of your professional life.
              </p>
              <ul className="space-y-4">
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Personalized AI Chat:</strong> Get instant answers to your career questions from your AI counselor.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Customizable Roadmaps:</strong> Adapt your plan as you grow with an easy-to-use interface.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Readiness Checklist:</strong> Track the skills and credentials you need to be job-ready.</span>
                </li>
              </ul>
               <Button asChild size="lg" className="mt-8">
                <Link href="/dashboard">Explore Your Dashboard <ArrowRight className="ml-2" /></Link>
              </Button>
            </div>
            <div className="relative aspect-square rounded-xl overflow-hidden shadow-2xl">
              {copilotImage && (
                <Image src={copilotImage.imageUrl} alt="Career Co-Pilot" fill className="object-cover" data-ai-hint={copilotImage.imageHint} />
              )}
            </div>
          </div>
        </section>
        
        <section id="career-preview" className="py-24">
          <div className="container text-center">
            <h2 className="font-headline text-3xl md:text-4xl font-bold">From Assessment to Action</h2>
            <p className="max-w-xl mx-auto text-muted-foreground mt-4 mb-12">
              Our AI doesn't just give you vague suggestions. It builds a tangible, step-by-step roadmap to guide you. Here's a glimpse of what your future could look like.
            </p>
            <Card className="max-w-2xl mx-auto text-left shadow-xl">
              <CardHeader>
                <CardTitle className="font-headline">Example Roadmap: UI/UX Designer</CardTitle>
                <p className="text-primary">Based on a passion for art, strong problem-solving skills, and a desire to create helpful technology.</p>
              </CardHeader>
              <CardContent className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-6">
                <div className="flex flex-col items-center">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold">1</div>
                  <div className="w-px h-full bg-border my-2"></div>
                </div>
                <div>
                  <h4 className="font-semibold">Foundation Building</h4>
                  <p className="text-muted-foreground text-sm">Enroll in an online UI/UX bootcamp (e.g., Coursera, General Assembly). Master Figma and Adobe XD.</p>
                </div>

                <div className="flex flex-col items-center">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold">2</div>
                  <div className="w-px h-full bg-border my-2"></div>
                </div>
                <div>
                  <h4 className="font-semibold">Build a Portfolio</h4>
                  <p className="text-muted-foreground text-sm">Complete 3-5 personal projects. Focus on creating detailed case studies for each, from problem to solution.</p>
                </div>
                
                <div className="flex flex-col items-center">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold">3</div>
                </div>
                <div>
                  <h4 className="font-semibold">Gain Experience & Network</h4>
                  <p className="text-muted-foreground text-sm">Start applying for internships or freelance work. Attend local and virtual design meetups to build connections.</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>

        <section id="testimonials" className="py-24 bg-card border-y">
            <div className="container">
                <div className="text-center mb-16">
                    <h2 className="font-headline text-3xl md:text-4xl font-bold">Loved by Professionals and Dreamers</h2>
                     <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                        See how IKI-G-AI has helped others find their path.
                    </p>
                </div>
                <div className="grid lg:grid-cols-3 gap-8">
                    {testimonials.map((testimonial) => {
                        const image = PlaceHolderImages.find((p) => p.id === testimonial.avatarId);
                        return (
                            <Card key={testimonial.name} className="flex flex-col justify-between p-6">
                                <CardContent className="p-0">
                                  <Quote className="w-8 h-8 text-primary/20 mb-4" />
                                  <p className="text-muted-foreground mb-6">{testimonial.quote}</p>
                                </CardContent>
                                <div className="flex items-center gap-4">
                                    {image && (
                                        <Avatar>
                                            <AvatarImage src={image.imageUrl} alt={testimonial.name} data-ai-hint={image.imageHint} />
                                            <AvatarFallback>{testimonial.name.charAt(0)}</AvatarFallback>
                                        </Avatar>
                                    )}
                                    <div>
                                        <p className="font-semibold text-foreground">{testimonial.name}</p>
                                        <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                                    </div>
                                </div>
                            </Card>
                        );
                    })}
                </div>
            </div>
        </section>

        <section id="faq" className="py-24">
          <div className="container max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="font-headline text-3xl md:text-4xl font-bold">Frequently Asked Questions</h2>
              <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                Have questions? We've got answers. Here are some of the most common things we get asked.
              </p>
            </div>
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="text-lg font-semibold text-left">{faq.question}</AccordionTrigger>
                  <AccordionContent className="text-base text-muted-foreground">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>

        <section id="newsletter" className="py-24 bg-primary/5 border-t">
          <div className="container">
            <div className="max-w-xl mx-auto text-center">
              <h2 className="font-headline text-3xl font-bold">Stay Ahead of the Curve</h2>
              <p className="mt-2 text-muted-foreground">
                Subscribe to our newsletter for the latest insights on career development, AI trends, and personal growth.
              </p>
              <form className="mt-6 flex max-w-md mx-auto" onSubmit={(e) => e.preventDefault()}>
                <Input 
                  type="email" 
                  placeholder="Enter your email"
                  className="flex-1 rounded-r-none focus-visible:ring-offset-0 focus-visible:ring-primary"
                  aria-label="Email for newsletter"
                />
                <Button type="submit" className="rounded-l-none">
                  Subscribe
                </Button>
              </form>
            </div>
          </div>
        </section>

      </main>
      <footer className="border-t bg-card">
        <div className="container py-6 text-center text-muted-foreground text-sm">
          <p>&copy; {new Date().getFullYear()} IKI-G-AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
