'use client';

import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Compass, Bot, Network, ArrowRight, ClipboardList, Route, MessageSquare, Quote } from 'lucide-react';
import Logo from '@/components/logo';
import { UserNav } from '@/components/user-nav';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { auth } from '@/lib/firebase';
import { onAuthStateChanged } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { Input } from '@/components/ui/input';

const features = [
  {
    icon: <Compass className="w-8 h-8 text-primary" />,
    title: 'Interactive Assessment',
    description: 'Uncover your passions, skills, and values through our comprehensive Ikigai assessment.',
    imageId: 'feature1',
  },
  {
    icon: <Bot className="w-8 h-8 text-primary" />,
    title: 'AI-Powered Recommendations',
    description: 'Receive personalized career paths and actionable roadmaps generated by our advanced AI.',
    imageId: 'feature2',
  },
  {
    icon: <Network className="w-8 h-8 text-primary" />,
    title: 'Dynamic Roadmap',
    description: 'Visualize your career journey, customize milestones, and track your progress towards success.',
    imageId: 'feature3',
  },
];

const howItWorksSteps = [
    {
        icon: <ClipboardList className="w-10 h-10 text-primary" />,
        title: "1. Take the Assessment",
        description: "Answer a series of thought-provoking questions to uncover your unique passions, strengths, and motivations."
    },
    {
        icon: <Route className="w-10 h-10 text-primary" />,
        title: "2. Generate Your Roadmap",
        description: "Our AI analyzes your results to create a personalized career roadmap with actionable steps and milestones."
    },
    {
        icon: <MessageSquare className="w-10 h-10 text-primary" />,
        title: "3. Chat with Your Counselor",
        description: "Refine your path and get answers to your questions with Kai, your personal AI career counselor."
    }
];

const testimonials = [
    {
        name: "Sarah L.",
        role: "Career Changer",
        quote: "IKI-G-AI gave me the clarity I was desperately looking for. The roadmap wasn't just a list of jobs; it was a genuine reflection of who I am. I finally feel confident in my career change.",
        avatarId: "testimonial1"
    },
    {
        name: "Michael B.",
        role: "Recent Graduate",
        quote: "As a recent grad, the job market felt overwhelming. This platform helped me connect my degree to a mission I care about. The AI counselor was surprisingly insightful for interview prep!",
        avatarId: "testimonial2"
    },
    {
        name: "Jessica Y.",
        role: "Product Manager",
        quote: "I was feeling stuck in my career. The Ikigai assessment helped me rediscover what I love, and the AI showed me how to pivot within my own company. It's been a game-changer.",
        avatarId: "testimonial3"
    }
];


const heroImage = PlaceHolderImages.find((p) => p.id === 'hero');
const copilotImage = PlaceHolderImages.find((p) => p.id === 'copilot');


export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState<boolean | null>(null);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setIsLoggedIn(!!user);
    });
    return () => unsubscribe();
  }, []);

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center">
          <Logo />
          <div className="flex flex-1 items-center justify-end space-x-4">
            {isLoggedIn !== null && (
              isLoggedIn ? <UserNav /> : (
                <Button asChild>
                  <Link href="/login">Sign In & Get Started</Link>
                </Button>
              )
            )}
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="relative pt-24 pb-32 md:pt-32 md:pb-40 lg:pt-40 lg:pb-48">
           {heroImage && (
            <Image
              src={heroImage.imageUrl}
              alt={heroImage.description}
              fill
              className="object-cover"
              priority
              data-ai-hint={heroImage.imageHint}
            />
          )}
          <div className="absolute inset-0 bg-background/60 backdrop-blur-sm" />
          <div className="container relative text-center">
            <div className="bg-accent/30 text-accent-foreground rounded-full px-4 py-1.5 text-sm font-medium bg-purple-500/20 text-purple-800 dark:text-purple-200 inline-block mb-4">
              Find Your Purpose. Build Your Future.
            </div>
            <h1 className="font-headline text-4xl md:text-6xl font-bold tracking-tighter mb-6 text-foreground">
              Navigate Your Career with <span className="text-primary">IKI-G-AI</span>
            </h1>
            <p className="max-w-2xl mx-auto text-lg text-foreground/80 mb-8">
              Discover your life's purpose and translate it into a personalized, AI-driven career roadmap.
            </p>
            <Button asChild size="lg">
              <Link href="/dashboard">Get Started Now</Link>
            </Button>
          </div>
        </section>

        <section id="features" className="py-24 bg-card border-y">
          <div className="container">
            <div className="text-center mb-16">
              <h2 className="font-headline text-3xl md:text-4xl font-bold">A Smarter Way to Plan Your Career</h2>
              <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                Our platform integrates self-discovery with AI precision to guide you on a fulfilling professional journey.
              </p>
            </div>
            <div className="grid md:grid-cols-3 gap-8">
              {features.map((feature) => {
                const image = PlaceHolderImages.find((p) => p.id === feature.imageId);
                return (
                  <Card key={feature.title} className="flex flex-col overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300">
                    <CardHeader className="flex flex-row items-center gap-4 p-6">
                      {feature.icon}
                      <CardTitle className="font-headline m-0">{feature.title}</CardTitle>
                    </CardHeader>
                    <CardContent className="flex-grow p-6 pt-0">
                      <p className="text-muted-foreground">{feature.description}</p>
                    </CardContent>
                    <div className="aspect-video relative">
                      {image && (
                        <Image src={image.imageUrl} alt={feature.title} fill className="object-cover" data-ai-hint={image.imageHint} />
                      )}
                    </div>
                  </Card>
                );
              })}
            </div>
          </div>
        </section>

        <section id="how-it-works" className="py-24">
            <div className="container">
                <div className="text-center mb-16">
                    <h2 className="font-headline text-3xl md:text-4xl font-bold">Your Journey to Purpose in 3 Simple Steps</h2>
                    <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                        We've streamlined the path to discovering and acting on your Ikigai.
                    </p>
                </div>
                <div className="grid md:grid-cols-3 gap-8 text-center">
                    {howItWorksSteps.map((step) => (
                        <div key={step.title} className="flex flex-col items-center">
                            <div className="flex items-center justify-center h-20 w-20 rounded-full bg-primary/10 mb-6">
                                {step.icon}
                            </div>
                            <h3 className="font-headline text-xl font-bold mb-2">{step.title}</h3>
                            <p className="text-muted-foreground">{step.description}</p>
                        </div>
                    ))}
                </div>
            </div>
        </section>

        <section className="py-24 bg-card border-y">
          <div className="container grid md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="font-headline text-3xl md:text-4xl font-bold">Your Personal Career Co-Pilot</h2>
              <p className="text-muted-foreground mt-4 mb-6">
                Go beyond static career advice. Our platform provides everything you need to take control of your professional life.
              </p>
              <ul className="space-y-4">
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Personalized AI Chat:</strong> Get instant answers to your career questions from your AI counselor.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Customizable Roadmaps:</strong> Adapt your plan as you grow with an easy-to-use interface.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Readiness Checklist:</strong> Track the skills and credentials you need to be job-ready.</span>
                </li>
              </ul>
               <Button asChild size="lg" className="mt-8">
                <Link href="/dashboard">Explore Your Dashboard <ArrowRight className="ml-2" /></Link>
              </Button>
            </div>
            <div className="relative aspect-square rounded-xl overflow-hidden shadow-2xl">
              {copilotImage && (
                <Image src={copilotImage.imageUrl} alt="Career Co-Pilot" fill className="object-cover" data-ai-hint={copilotImage.imageHint} />
              )}
            </div>
          </div>
        </section>

        <section id="testimonials" className="py-24">
            <div className="container">
                <div className="text-center mb-16">
                    <h2 className="font-headline text-3xl md:text-4xl font-bold">Loved by Professionals and Dreamers</h2>
                     <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                        See how IKI-G-AI has helped others find their path.
                    </p>
                </div>
                <div className="grid lg:grid-cols-3 gap-8">
                    {testimonials.map((testimonial) => {
                        const image = PlaceHolderImages.find((p) => p.id === testimonial.avatarId);
                        return (
                            <Card key={testimonial.name} className="flex flex-col justify-between p-6">
                                <CardContent className="p-0">
                                  <Quote className="w-8 h-8 text-primary/20 mb-4" />
                                  <p className="text-muted-foreground mb-6">{testimonial.quote}</p>
                                </CardContent>
                                <div className="flex items-center gap-4">
                                    {image && (
                                        <Avatar>
                                            <AvatarImage src={image.imageUrl} alt={testimonial.name} data-ai-hint={image.imageHint} />
                                            <AvatarFallback>{testimonial.name.charAt(0)}</AvatarFallback>
                                        </Avatar>
                                    )}
                                    <div>
                                        <p className="font-semibold text-foreground">{testimonial.name}</p>
                                        <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                                    </div>
                                </div>
                            </Card>
                        );
                    })}
                </div>
            </div>
        </section>

        <section id="newsletter" className="py-24 bg-primary/5 border-t">
          <div className="container">
            <div className="max-w-xl mx-auto text-center">
              <h2 className="font-headline text-3xl font-bold">Stay Ahead of the Curve</h2>
              <p className="mt-2 text-muted-foreground">
                Subscribe to our newsletter for the latest insights on career development, AI trends, and personal growth.
              </p>
              <form className="mt-6 flex max-w-md mx-auto" onSubmit={(e) => e.preventDefault()}>
                <Input 
                  type="email" 
                  placeholder="Enter your email"
                  className="flex-1 rounded-r-none focus-visible:ring-offset-0 focus-visible:ring-primary"
                  aria-label="Email for newsletter"
                />
                <Button type="submit" className="rounded-l-none">
                  Subscribe
                </Button>
              </form>
            </div>
          </div>
        </section>

      </main>
      <footer className="border-t bg-card">
        <div className="container py-6 text-center text-muted-foreground text-sm">
          <p>&copy; {new Date().getFullYear()} IKI-G-AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
