import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Compass, Bot, Network } from 'lucide-react';
import Logo from '@/components/logo';
import { UserNav } from '@/components/user-nav';

const features = [
  {
    icon: <Compass className="w-8 h-8 text-primary" />,
    title: 'Interactive Assessment',
    description: 'Uncover your passions, skills, and values through our comprehensive Ikigai assessment.',
    image: { id: "1", src: "https://picsum.photos/seed/feature1/600/400", hint: "person thinking" },
  },
  {
    icon: <Bot className="w-8 h-8 text-primary" />,
    title: 'AI-Powered Recommendations',
    description: 'Receive personalized career paths and actionable roadmaps generated by our advanced AI.',
    image: { id: "2", src: "https://picsum.photos/seed/feature2/600/400", hint: "futuristic interface" },
  },
  {
    icon: <Network className="w-8 h-8 text-primary" />,
    title: 'Dynamic Roadmap',
    description: 'Visualize your career journey, customize milestones, and track your progress towards success.',
    image: { id: "3", src: "https://picsum.photos/seed/feature3/600/400", hint: "path mountain" },
  },
];

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center">
          <Logo />
          <div className="flex flex-1 items-center justify-end space-x-4">
            <UserNav />
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-24 md:py-32 lg:py-40">
          <div className="container text-center">
            <div className="bg-accent/30 rounded-full px-4 py-1.5 text-sm font-medium text-primary inline-block mb-4">
              Find Your Purpose. Build Your Future.
            </div>
            <h1 className="font-headline text-4xl md:text-6xl font-bold tracking-tighter mb-6">
              Navigate Your Career with <span className="text-primary">Ikigai</span>
            </h1>
            <p className="max-w-2xl mx-auto text-lg text-muted-foreground mb-8">
              Ikigai Navigator helps you discover your life's purpose and translates it into a personalized, AI-driven career roadmap.
            </p>
            <Button asChild size="lg">
              <Link href="/dashboard">Get Started Now</Link>
            </Button>
          </div>
        </section>

        <section id="features" className="py-24 bg-card border-t">
          <div className="container">
            <div className="text-center mb-16">
              <h2 className="font-headline text-3xl md:text-4xl font-bold">A Smarter Way to Plan Your Career</h2>
              <p className="max-w-xl mx-auto text-muted-foreground mt-4">
                Our platform integrates self-discovery with AI precision to guide you on a fulfilling professional journey.
              </p>
            </div>
            <div className="grid md:grid-cols-3 gap-8">
              {features.map((feature) => (
                <Card key={feature.title} className="flex flex-col overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300">
                  <CardHeader className="flex flex-row items-center gap-4 p-6">
                    {feature.icon}
                    <CardTitle className="font-headline m-0">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="flex-grow p-6 pt-0">
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                  <div className="aspect-video relative">
                    <Image src={feature.image.src} alt={feature.title} fill className="object-cover" data-ai-hint={feature.image.hint} />
                  </div>
                </Card>
              ))}
            </div>
          </div>
        </section>

        <section className="py-24">
          <div className="container grid md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="font-headline text-3xl md:text-4xl font-bold">Your Personal Career Co-Pilot</h2>
              <p className="text-muted-foreground mt-4 mb-6">
                Go beyond static career advice. Our platform provides everything you need to take control of your professional life.
              </p>
              <ul className="space-y-4">
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Personalized AI Chat:</strong> Get instant answers to your career questions from your AI counselor.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Customizable Roadmaps:</strong> Adapt your plan as you grow with an easy-to-use interface.</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                  <span><strong className="text-foreground">Readiness Checklist:</strong> Track the skills and credentials you need to be job-ready.</span>
                </li>
              </ul>
            </div>
            <div className="relative aspect-square rounded-xl overflow-hidden shadow-2xl">
                <Image src="https://picsum.photos/seed/copilot/600/600" alt="Career Co-Pilot" fill className="object-cover" data-ai-hint="woman working laptop" />
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t bg-card">
        <div className="container py-6 text-center text-muted-foreground text-sm">
          <p>&copy; {new Date().getFullYear()} Ikigai Navigator. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
